version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    env_file:
      - .env
    environment:
      - OLLAMA_DEBUG=error

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  mysql:
    image: mysql:8.0
    container_name: database-mysql
    restart: always
    ports:
      - "${DB_PORT_EXTERNA:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  projeto:
    build:
      context: .
    container_name: projeto-integrador
    depends_on:
      - ollama
      - mysql
    volumes:
      - .:/app
      - ./pdfs-excels:/app/pdfs-excels
    working_dir: /app
    command: ["sh", "/app/startup.sh"]
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: API
    ports:
      - "${API_PORT:-5000}:5000"
    restart: always
    depends_on:
      - projeto
      - qdrant           # << agora a API só arranca depois do Qdrant
    volumes:
      - ./app:/app
      - ./pdfs-excels:/app/pdfs-excels
      - ./ollama-progress.log:/app/ollama-progress.log
      - ./app/Frontend/static:/app/Frontend/static
     # - ollama-data:/root/.ollama   # (opcional; não é necessário para usar a API do Ollama)
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      # URLs internas na rede do compose
      OLLAMA_BASE_URL: http://ollama:11434
      QDRANT_URL: http://qdrant:6333
      # Modelos que vamos usar no Chatbot (ajusta se quiseres)
      CHAT_MODEL: mistral
      EMB_MODEL: nomic-embed-text
      TOPK: "5"

  frontend:
    image: nginx:latest
    container_name: projeto-frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./app/Frontend:/usr/share/nginx/html
    depends_on:
      - api
    env_file:
      - .env

volumes:
  ollama-data:
  mysql_data:
  qdrant_data:
