version: '3.9'

services:
  app:
    build: .
    container_name: projeto_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./pdfs-excels:/app/pdfs-excels
    depends_on:
      - db
      - ollama
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=meubanco
      - OLLAMA_URL=http://ollama:11434/api/chat  
      - OLLAMA_MODEL=mistral
    networks:
      - projeto_net
    command: >
      sh -c "sleep 10 && python ProjetoFinal.py"  

  db:
    image: mysql:8.0
    container_name: projeto_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - projeto_net

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: projeto_ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - projeto_net
    restart: always

volumes:
  mysql_data:
  ollama_data:

networks:
  projeto_net:
